name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Set Up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache-dependency-path: 'go.sum'

    - name: Get Dependencies
      run: go get -v ...

    - name: Build
      run: go build -v src/*.go