name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Demo Server
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache-dependency-path: 'go.sum'

    - name: Get dependencies
      run: go get -v ...

    - name: Build
      run: go build -v src/*.go